### ISSUE TITLE
[Suggestion] Remove `1.1.1.1` DNS server beacause it's blocked in China since 2023/10/01

### ISSUE THREAD

**Issue by Fallen-Breath** [pterodactyl-china/wings#11]
See: https://github.com/net4people/bbs/issues/295

Related code:

https://github.com/pterodactyl-china/wings/blob/5b704dec26621e84ef22b2ffb9d5e5017c2a60e1/config/config_docker.go#L28C1-L29

**Comment by vlssu** [comment]
谢谢你的建议，已做修改。
